android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.enableJetifier=false
kotlin.daemon.jvmargs=-Xmx2048M
org.gradle.parallel=true
org.gradle.caching=true

org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
#android.enableJetifier=true

# Force Java 17 for all modules
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17

# Kotlin options
kotlin.code.style=official
# Disable incremental compilation to avoid cache issues
kotlin.incremental=false

# Use Java 17
java.sourceCompatibility=17
java.targetCompatibility=17

# Better error messages
org.gradle.warning.mode=all

# Suppress compileSdk warning
android.suppressUnsupportedCompileSdk=36
kotlin.jvm.target.validation.mode = IGNORE

